# Generated by Django 3.1.6 on 2021-11-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0004_auto_20211113_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupUserRelate',
        ),
    ]
