# Generated by Django 3.1.6 on 2021-11-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0006_splitgroup_gid'),
    ]

    operations = [
        migrations.AddField(
            model_name='splituser',
            name='Uid',
            field=models.IntegerField(null=True, verbose_name='211115210126669'),
        ),
        migrations.AlterField(
            model_name='splitgroup',
            name='Gid',
            field=models.IntegerField(null=True, verbose_name='21111521012666'),
        ),
    ]
