# Generated by Django 3.1.6 on 2021-11-18 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0011_auto_20211115_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Aweighted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
