# Generated by Django 3.1.6 on 2021-11-18 14:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0012_activity_aweighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='AMoney',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='Aweighted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], null=True, size=None),
        ),
    ]
