# Generated by Django 3.1.6 on 2021-11-18 15:01

import django.contrib.postgres.fields
from django.db import migrations, models
import split.models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0013_auto_20211118_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='AMoney',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=split.models.g_limits, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='Aweighted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=split.models.g_limits, null=True, size=None),
        ),
    ]
