# Generated by Django 3.1.6 on 2021-12-20 21:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0014_auto_20211118_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Ajoined',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], null=True, size=None),
        ),
    ]
