# Generated by Django 3.1.6 on 2021-12-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0015_activity_ajoined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Ajoined',
        ),
    ]
