# Generated by Django 3.1.6 on 2021-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0003_auto_20211113_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splituser',
            name='joinedGroup',
            field=models.ManyToManyField(blank=True, related_name='joinUsers', to='split.SplitGroup'),
        ),
    ]
