# Generated by Django 3.1.6 on 2021-11-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0007_auto_20211115_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitgroup',
            name='Gid',
            field=models.IntegerField(default='21111521042245', null=True),
        ),
        migrations.AlterField(
            model_name='splituser',
            name='Uid',
            field=models.IntegerField(default='211115210422458', null=True),
        ),
    ]
