# Generated by Django 3.1.6 on 2021-11-15 21:13

from django.db import migrations, models
import split.models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0009_auto_20211115_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitgroup',
            name='Gid',
            field=models.IntegerField(default=split.models.gen_id, null=True),
        ),
        migrations.AlterField(
            model_name='splituser',
            name='Uid',
            field=models.IntegerField(default=split.models.gen_id, null=True),
        ),
    ]
